name: OSCompiler

on:
  push:
    branches: main

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.6'
        include-vcbuild: true

    - name: Install COSMOS Dev Kit (1/2)
      run: |
        git clone https://github.com/CosmosOS/Cosmos.git --depth 1
        cd Cosmos
      shell: pwsh
    
    - name: Install COSMOS Dev Kit (2/2)
      run: |
          cd D:\a\flexOS\flexOS\Cosmos
          dir
          install-VS2022.bat
      shell: cmd

    - name: Restore NuGet packages
      run: nuget restore VivDOS.sln
      shell: pwsh