name: OSCompiler

on:
  push:
    branches: main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Install dependencies
        run: sudo apt-get install yasm

      - name: Restore dependencies and install Cosmos.Build.Builder
        run: |
          dotnet new tool-manifest
          dotnet tool install Cosmos.Build.Builder --version 2023.6.3 # Устанавливаем Cosmos

      - name: Build flexOS
        run: |
          dotnet restore
          dotnet build

      - name: Run Cosmos Build
        run: dotnet cosmos build

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with: 
          name: flexOS.iso
          path: bin/Debug/net6.0/flexOS.iso