name: OSCompiler

on:
  push:
      branches: main

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup packages
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
        run: sudo apt-get install make, yasm
      - name: Clone Cosmos
        run: |
          git clone https://github.com/CosmosOS/Cosmos
          git clone https://github.com/CosmosOS/IL2CPU
          git clone https://github.com/CosmosOS/XSharp
          git clone https://github.com/CosmosOS/Common
      - name: Clone IL2CPU
        run: git clone https://github.com/CosmosOS/IL2CPU
      - name: Clone X#
        run: git clone https://github.com/CosmosOS/XSharp
      - name: Clone Common
        run: git clone https://github.com/CosmosOS/Common
      - name: Build Cosmos
        run: cd Cosmos; make
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: sudo dotnet build --no-restore