name: OSCompiler

on:
  push:
    branches: main

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.6'
        include-vcbuild: true

    - name: Install COSMOS Dev Kit
      run: |
        git clone https://github.com/CosmosOS/Cosmos.git --depth 1
        cd Cosmos
        install-VS2022.bat
      shell: cmd

    - name: Build ISO
      run: |
        nuget restore flexOS.sln
        msbuild /p:Configuration=Release flexOS.sln