name: OSCompiler

on:
  push:
      branches: main

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Clone Cosmos
        run: git clone https://github.com/CosmosOS/Cosmos
      - name: Clone IL2CPU
        run: git clone https://github.com/CosmosOS/IL2CPU
      - name: Clone X#
        run: git clone https://github.com/CosmosOS/XSharp
      - name: Clone Common
        run: git clone https://github.com/CosmosOS/Common
      - name: Build Cosmos
        run: cd Cosmos; make build; make install; cd ..
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore